import { ArrowLeft } from 'lucide-react'
import { Link } from '../router'
import ThemeToggle from '../components/ThemeToggle'

const GENERAL_EMAIL = 'mynexamodel@gmail.com'
const PRIVACY_EMAIL = 'itszinniraahmad@gmail.com'

const sections = [
  ['Personal data, technical data and sources', 'Data peribadi, data teknikal dan sumber',
    'We collect information you provide directly, including identity and contact details, age, location, social profiles, measurements, experience, preferences, availability, declarations, notes, photos, videos and later training materials. We and our security providers also process technical data generated when you use the service, including IP address, request and security logs, timestamps, browser or device information, network headers, Turnstile results, application references and upload events. Information may later come from your WhatsApp communications, Google Drive training submissions, Nexa Model staff and relevant brand or client feedback if your application progresses.',
    'Kami mengumpul maklumat yang anda berikan secara langsung, termasuk butiran identiti dan hubungan, umur, lokasi, profil sosial, ukuran, pengalaman, pilihan, ketersediaan, pengisytiharan, nota, gambar dan bahan latihan. Kami dan penyedia keselamatan kami turut memproses data teknikal yang dijana apabila anda menggunakan perkhidmatan ini, termasuk alamat IP, log permintaan dan keselamatan, cap masa, maklumat pelayar atau peranti, header rangkaian, keputusan Turnstile, rujukan permohonan dan peristiwa muat naik. Maklumat kemudian mungkin datang daripada komunikasi WhatsApp anda, penghantaran latihan Google Drive, kakitangan Nexa Model dan maklum balas jenama atau client yang berkaitan jika permohonan anda diteruskan.'],
  ['Required and optional information', 'Maklumat wajib dan pilihan',
    'Fields marked with an asterisk and every stated minimum photos are required to submit and assess an application. If you do not provide them, Nexa Model cannot complete the application, contact you through the selected channel or assess your suitability. Unmarked fields are voluntary; leaving them blank will not by itself prevent submission, but may reduce the context available for matching, training or assessment.',
    'Petak bertanda asterisk dan setiap bilangan minimum gambar yang dinyatakan adalah wajib untuk menghantar dan menilai permohonan. Jika anda tidak memberikannya, Nexa Model tidak dapat melengkapkan permohonan, menghubungi anda melalui saluran yang dipilih atau menilai kesesuaian anda. Petak tanpa tanda adalah pilihan; membiarkannya kosong tidak akan menggagalkan permohonan, tetapi mungkin mengurangkan konteks untuk padanan, latihan atau penilaian.'],
  ['Purposes and decisions', 'Tujuan dan keputusan',
    'We process the information to verify secure access, prevent abuse, receive and manage applications, assess suitability, communicate about applications, conduct training or assessment, consider candidates for relevant casting, honour sharing choices, maintain records, troubleshoot the service, protect legal rights and comply with applicable law. Selection decisions are reviewed by authorized people and are not made solely by automated processing.',
    'Kami memproses maklumat untuk mengesahkan akses selamat, mencegah penyalahgunaan, menerima dan mengurus permohonan, menilai kesesuaian, berhubung mengenai permohonan, menjalankan latihan atau penilaian, mempertimbangkan calon untuk casting berkaitan, menghormati pilihan perkongsian, menyimpan rekod, menyelesaikan masalah perkhidmatan, melindungi hak undang-undang dan mematuhi undang-undang yang terpakai. Keputusan pemilihan disemak oleh individu yang dibenarkan dan tidak dibuat semata-mata melalui pemprosesan automatik.'],
  ['Sharing and service providers', 'Perkongsian dan penyedia perkhidmatan',
    'Access is limited to authorized Nexa Model personnel and service providers that need the data for an identified purpose. Cloudflare provides website delivery, security, Turnstile and database services; ImageKit stores private application photos and videos; Resend delivers application emails; WhatsApp, operated by Meta, may be used to contact you with your consent; and Google Drive may receive training photos or videos from shortlisted candidates. A profile is shared with a suitable brand or client only where your recorded choice permits it. We may also disclose data to professional advisers, law-enforcement bodies or regulators where reasonably necessary or legally required. We do not sell applicant personal data.',
    'Akses dihadkan kepada kakitangan Nexa Model yang dibenarkan dan penyedia perkhidmatan yang memerlukan data bagi tujuan yang dikenal pasti. Cloudflare menyediakan penghantaran laman web, keselamatan, Turnstile dan perkhidmatan pangkalan data; ImageKit menyimpan gambar permohonan secara private; Resend menghantar e-mel permohonan; WhatsApp yang dikendalikan oleh Meta mungkin digunakan untuk menghubungi anda dengan persetujuan anda; dan Google Drive mungkin menerima gambar atau video latihan daripada calon yang disenarai pendek. Profil hanya dikongsi dengan jenama atau client yang sesuai apabila anda bersetuju. Kami juga mungkin mendedahkan data kepada penasihat profesional, badan penguatkuasaan undang-undang atau pengawal selia apabila diperlukan secara munasabah atau diwajibkan undang-undang. Kami tidak menjual data peribadi pemohon.'],
  ['Processing outside Malaysia', 'Pemprosesan di luar Malaysia',
    'Cloudflare, ImageKit, Resend, Meta or Google may process or store personal data in countries outside Malaysia to provide their services. Those transfers are limited to the stated purposes. Nexa Model will use an applicable condition under section 129 of Malaysia’s Personal Data Protection Act 2010 and take reasonable precautions, including provider security controls and appropriate contractual protections. Where consent is the applicable condition, the application declaration records your consent to the necessary transfer. You may withdraw consent for future processing, although this may prevent Nexa Model from continuing an application or using the affected service.',
    'Cloudflare, ImageKit, Resend, Meta atau Google mungkin memproses atau menyimpan data peribadi di negara di luar Malaysia untuk menyediakan perkhidmatan mereka. Pemindahan tersebut dihadkan kepada tujuan yang dinyatakan. Nexa Model akan menggunakan syarat yang terpakai di bawah seksyen 129 Akta Perlindungan Data Peribadi 2010 Malaysia dan mengambil langkah berjaga-jaga yang munasabah, termasuk kawalan keselamatan penyedia dan perlindungan kontrak yang sesuai. Apabila persetujuan ialah syarat yang terpakai, pengisytiharan permohonan merekodkan persetujuan anda terhadap pemindahan yang diperlukan. Anda boleh menarik balik persetujuan untuk pemprosesan masa hadapan, walaupun ini mungkin menghalang Nexa Model daripada meneruskan permohonan atau menggunakan perkhidmatan yang terjejas.'],
  ['Retention', 'Tempoh penyimpanan',
    'Application information and photos and videos are normally scheduled for review and deletion six months after submission or last meaningful activity. A record may be kept longer while you remain shortlisted, participate in training or an assignment, resolve a request or dispute, or where law or a documented operational need requires it. Secure access and recovery links expire after 60 minutes. Providers may retain limited security and delivery logs under their applicable retention settings. Data that is no longer required will be deleted or anonymized through Nexa Model’s retention process.',
    'Maklumat permohonan dan gambar biasanya direkodkan untuk semakan dan pemadaman enam bulan selepas penghantaran atau sebarang aktiviti dan latihan terakhir. Rekod mungkin disimpan lebih lama semasa anda masih disenarai pendek, menyertai latihan atau tugasan, menyelesaikan permintaan atau pertikaian, atau apabila undang-undang atau keperluan operasi yang didokumenkan memerlukannya. Pautan akses selamat dan recovery tamat tempoh selepas 60 minit. Penyedia mungkin menyimpan log keselamatan dan penghantaran yang terhad mengikut tetapan penyimpanan mereka. Data yang tidak lagi diperlukan akan dipadam melalui proses penyimpanan Nexa Model.'],
  ['Your choices and rights', 'Pilihan dan hak anda',
    'You may ask whether we hold your personal data and request access, correction, deletion, withdrawal of consent or data portability where applicable and technically feasible. You may also change your choice about profile sharing or WhatsApp contact. Withdrawal does not affect processing already carried out with valid consent or another lawful requirement. We may verify your identity and may retain information where an applicable law permits or requires it.',
    'Anda boleh bertanya sama ada kami menyimpan data peribadi anda dan meminta akses, pembetulan, pemadaman, penarikan balik persetujuan atau mudah alih data jika berkenaan dan boleh dilaksanakan secara teknikal. Anda juga boleh mengubah pilihan mengenai perkongsian profil atau hubungan WhatsApp. Penarikan balik tidak menjejaskan pemprosesan yang telah dilakukan dengan persetujuan sah atau keperluan undang-undang lain. Kami mungkin mengesahkan identiti anda dan mungkin menyimpan maklumat apabila undang-undang yang terpakai membenarkan atau mewajibkannya.'],
  ['Security', 'Keselamatan',
    'We use access controls, administrator authentication, bot protection, rate limits, private image storage, hashed single-use tokens, request-size limits and time-limited image links. No online system can guarantee absolute security. Access is restricted to authorized operational purposes and security measures are reviewed as the service changes.',
    'Kami menggunakan kawalan akses, pengesahan pentadbir, perlindungan bot, rate limit, penyimpanan gambar private, token sekali guna yang di-hash, had saiz permintaan dan pautan gambar bertempoh. Tiada sistem dalam talian dapat menjamin keselamatan mutlak. Akses dihadkan kepada tujuan operasi yang dibenarkan dan langkah keselamatan disemak apabila perkhidmatan berubah.'],
  ]

export default function Privacy() {
  return <main className="privacy-page">
    <header className="privacy-header"><Link className="back-link" to="/"><ArrowLeft size={17} /> Back to website</Link><ThemeToggle /></header>
    <article className="privacy-content">
      <p className="section-label">NEXA MODEL</p>
      <h1>Privacy Notice</h1>
      <p className="privacy-bm-title">Notis Privasi</p>
      <p className="privacy-lead">Nexa Model is an online-only talent operation run by Zinnira Ahmad. Zinnira Ahmad is the data controller for personal data processed through this service.</p>
      <p className="bm-text">Nexa Model ialah operasi bakat secara dalam talian yang dikendalikan oleh Zinnira Ahmad. Zinnira Ahmad ialah pengawal data bagi data peribadi yang diproses melalui perkhidmatan ini.</p>
      {sections.map(([title, titleBm, text, textBm]) => <section key={title}><h2>{title}</h2><h3>{titleBm}</h3><p>{text}</p><p className="bm-text">{textBm}</p></section>)}
      <section><h2>Controller and contact details</h2><h3>Butiran pengawal dan hubungan</h3><p>Data controller: Zinnira Ahmad, operating Nexa Model as an online-only talent operation. General electronic correspondence: <a href={`mailto:${GENERAL_EMAIL}`}>{GENERAL_EMAIL}</a>. Privacy requests and complaints: <a href={`mailto:${PRIVACY_EMAIL}`}>{PRIVACY_EMAIL}</a>.</p><p className="bm-text">Pengawal data: Zinnira Ahmad, mengendalikan Nexa Model sebagai operasi bakat secara dalam talian. Surat-menyurat elektronik umum: <a href={`mailto:${GENERAL_EMAIL}`}>{GENERAL_EMAIL}</a>. Permintaan dan aduan privasi: <a href={`mailto:${PRIVACY_EMAIL}`}>{PRIVACY_EMAIL}</a>.</p></section>
      <section><h2>Changes and language</h2><h3>Perubahan dan bahasa</h3><p>We may update this notice when the application process, providers or legal requirements change. Material changes will be published here with a new effective date. The English and Bahasa Malaysia versions are intended to have the same meaning; please contact us if anything appears inconsistent.</p><p className="bm-text">Kami mungkin mengemas kini notis ini apabila proses permohonan, penyedia atau keperluan undang-undang berubah. Perubahan penting akan diterbitkan di sini dengan tarikh berkuat kuasa baharu. Versi bahasa Inggeris dan Bahasa Malaysia bertujuan membawa maksud yang sama; sila hubungi kami jika terdapat percanggahan.</p></section>
      <small>Effective date: 8 August 2026 · Tarikh berkuat kuasa: 8 Ogos 2026</small>
    </article>
  </main>
}
